apiVersion: apps/v1
kind: Deployment
metadata:
  name: ros2-multi-topic-publisher
  labels:
    app: ros2-multi-topic-publisher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ros2-multi-topic-publisher
  template:
    metadata:
      labels:
        app: ros2-multi-topic-publisher
    spec:
      containers:
        - name: ros2-multi-topic-publisher
          image: ghcr.io/YOUR_GH_USERNAME/ros2-multi-topic-publisher:latest
          env:
            - name: FREQUENCY_HZ
              value: "2.0"
            - name: TOPICS
              value: "/topic1,/topic2"
            - name: PAYLOAD
              value: "hello from k8s + ROS2"
